---
# Inventaire généré automatiquement depuis Terraform
# Généré le: Tue Oct  7 15:43:39 GMT 2025
# Ne pas modifier manuellement - utiliser ./generate_inventory.sh

all:
  children:
    masters:
      hosts:
        k8s-cluster-master-1:
          ansible_host: 18.171.157.109
          private_ip: 10.0.1.245
          instance_id: i-096d895407a1ac8dc
          availability_zone: eu-west-2a
    workers:
      hosts:
        k8s-cluster-worker-1:
          ansible_host: 35.178.161.97
          private_ip: 10.0.1.223
          instance_id: i-0cd2fd6403fc969a3
          availability_zone: eu-west-2a
        k8s-cluster-worker-2:
          ansible_host: 18.133.236.199
          private_ip: 10.0.2.196
          instance_id: i-0cf935538d85320e5
          availability_zone: eu-west-2b
        k8s-cluster-worker-3:
          ansible_host: 18.175.245.90
          private_ip: 10.0.3.240
          instance_id: i-09b01ccf057f77dd4
          availability_zone: eu-west-2c
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
